name: Deploy Web App to Storage

on:
  push:
    branches:
      - main
    paths:
      - 'device-loan-web/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install and Build
        working-directory: ./device-loan-web
        run: |
          npm ci
          npm run build
          
      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --destination '$web' \
              --source ./device-loan-web/dist \
              --account-name cdlswebf5177547 \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --overwrite
